"""Seed PT→ES translations for bootstrap and smoke tests."""

SEED_PT_ES: dict[str, list[str]] = {
    "pegar": ["coger", "agarrar", "tomar"],
    "ficar": ["quedar", "permanecer"],
    "achar": ["encontrar", "pensar"],
    "jeito": ["manera", "modo"],
    "saudade": ["nostalgia", "añoranza"],
    "andar": ["caminar"],
    "trazer": ["traer"],
    "puxar": ["tirar", "jalar"],
    "chegar": ["llegar"],
    "deixar": ["dejar"],
    "falar": ["hablar"],
    "gostar": ["gustar"],
    "precisar": ["necesitar"],
    "procurar": ["buscar"],
    "levar": ["llevar"],
    "vir": ["venir"],
    "dar": ["dar"],
    "ter": ["tener"],
    "ser": ["ser"],
    "estar": ["estar"],
    "fazer": ["hacer"],
    "dizer": ["decir"],
    "poder": ["poder"],
    "querer": ["querer"],
    "saber": ["saber"],
    "haver": ["haber"],
    "ir": ["ir"],
    "ver": ["ver"],
    "pôr": ["poner"],
    "trabalhar": ["trabajar"],
    "trabalho": ["trabajo"],
    "morar": ["vivir", "residir"],
    "comer": ["comer"],
    "beber": ["beber"],
    "dormir": ["dormir"],
    "correr": ["correr"],
    "abrir": ["abrir"],
    "fechar": ["cerrar"],
    "entrar": ["entrar"],
    "sair": ["salir"],
    "subir": ["subir"],
    "descer": ["bajar"],
    "voltar": ["volver"],
    "começar": ["empezar", "comenzar"],
    "acabar": ["terminar", "acabar"],
    "continuar": ["continuar"],
    "esperar": ["esperar"],
    "encontrar": ["encontrar"],
    "perder": ["perder"],
    "ganhar": ["ganar"],
    "vender": ["vender"],
    "comprar": ["comprar"],
    "pagar": ["pagar"],
    "custar": ["costar"],
    "valer": ["valer"],
    "servir": ["servir"],
    "ajudar": ["ayudar"],
    "mandar": ["mandar", "enviar"],
    "receber": ["recibir"],
    "enviar": ["enviar"],
    "ligar": ["llamar", "conectar"],
    "chamar": ["llamar"],
    "perguntar": ["preguntar"],
    "responder": ["responder"],
    "explicar": ["explicar"],
    "entender": ["entender"],
    "aprender": ["aprender"],
    "ensinar": ["enseñar"],
    "estudar": ["estudiar"],
    "casa": ["casa"],
    "tempo": ["tiempo"],
    "dia": ["día"],
    "ano": ["año"],
    "país": ["país"],
    "cidade": ["ciudad"],
    "gente": ["gente"],
    "pessoa": ["persona"],
    "homem": ["hombre"],
    "mulher": ["mujer"],
    "criança": ["niño", "niña"],
    "água": ["agua"],
    "comida": ["comida"],
    "dinheiro": ["dinero"],
    "governo": ["gobierno"],
    "empresa": ["empresa"],
    "hospital": ["hospital"],
    "problema": ["problema"],
    "importante": ["importante"],
    "diferente": ["diferente"],
    "animal": ["animal"],
    "grande": ["grande"],
    "novo": ["nuevo"],
    "bom": ["bueno"],
    "mau": ["malo"],
    "não": ["no"],
    "nao": ["no"],
    "também": ["también"],
    "muito": ["mucho"],
    "ainda": ["aún", "todavía"],
    "sempre": ["siempre"],
    "nunca": ["nunca"],
    "agora": ["ahora"],
    "ontem": ["ayer"],
    "hoje": ["hoy"],
    "depois": ["después"],
    "antes": ["antes"],
    "mesmo": ["mismo"],
    "outro": ["otro"],
    "todo": ["todo"],
    "cada": ["cada"],
    "qualquer": ["cualquier"],
    "algum": ["algún"],
    "nenhum": ["ningún"],
    "mundo": ["mundo"],
    "vida": ["vida"],
    "nome": ["nombre"],
    "parte": ["parte"],
    "lugar": ["lugar"],
    "estado": ["estado"],
    "sistema": ["sistema"],
    "processo": ["proceso"],
    "programa": ["programa"],
    "projeto": ["proyecto"],
    "resultado": ["resultado"],
    "presidente": ["presidente"],
    "ministro": ["ministro"],
    "relação": ["relación"],
    "milhão": ["millón"],
    "bilhão": ["mil millones"],
    "seleção": ["selección"],
    "pesquisa": ["investigación", "búsqueda"],
    "conhecer": ["conocer"],
    "escrever": ["escribir"],
    "ler": ["leer"],
    "pensar": ["pensar"],
    "sentir": ["sentir"],
    "viver": ["vivir"],
    "morrer": ["morir"],
    "nascer": ["nacer"],
    "crescer": ["crecer"],
    "mudar": ["cambiar"],
    "seguir": ["seguir"],
    "passar": ["pasar"],
    "olhar": ["mirar", "ver"],
    "ouvir": ["oír"],
    "sentar": ["sentar"],
    "levantar": ["levantar"],
    "corpo": ["cuerpo"],
    "cabeça": ["cabeza"],
    "mão": ["mano"],
    "olho": ["ojo"],
    "livro": ["libro"],
    "porta": ["puerta"],
    "rua": ["calle"],
    "carro": ["coche", "carro"],
    "avião": ["avión"],
    "barco": ["barco"],
    "guerra": ["guerra"],
    "paz": ["paz"],
    "amor": ["amor"],
    "medo": ["miedo"],
    "feliz": ["feliz"],
    "triste": ["triste"],
    "fácil": ["fácil"],
    "difícil": ["difícil"],
    "rápido": ["rápido"],
    "lento": ["lento"],
    "pequeno": ["pequeño"],
    "brasileiro": ["brasileño"],
    "português": ["portugués"],
    "espanhol": ["español"],
    "inglês": ["inglés"],
    "francês": ["francés"],
    "alemão": ["alemán"],
    "japonês": ["japonés"],
    "chinês": ["chino"],
    "dever": ["deber"],
}

# Lemmas the LLM repeatedly fails on (accents, hyphens, short function words).
MANUAL_MISSING_PT_ES: dict[str, list[str]] = {
    "decisão": ["decisión"],
    "tão": ["tan"],
    "taxa": ["tasa", "impuesto"],
    "através": ["mediante", "través"],
    "apesar": ["pese", "aunque"],
    "portanto": ["entonces", "por tanto"],
    "contudo": ["empero", "sin embargo"],
    "senão": ["sino"],
    "entressafra": ["barbecho"],
    "fitar": ["mirar", "observar"],
    "priori": ["apriori"],
    "conseguinte": ["consiguiente"],
    "contracenar": ["contrarrestar", "actuar"],
    "minhocão": ["gusano"],
    "batom": ["pintalabios"],
    "maresia": ["salitre"],
    "fim-de-semana": ["fin-de-semana"],
    "mão-de-obra": ["mano-de-obra"],
    "primeiro-ministro": ["primer-ministro"],
    "matéria-prima": ["materia-prima"],
    "secretário-geral": ["secretario-general"],
    "data-base": ["basedatos"],
    "procurador-geral": ["procurador-general"],
    "quarta-de-final": ["cuartos-de-final"],
    "sem-terra": ["sin-tierra"],
    "lateral-esquerdo": ["lateral-izquierdo"],
    "cessar-fogo": ["cese-fuego", "tregua"],
    "carro-forte": ["coche-blindado", "furgón"],
    "primeira-dama": ["primera-dama"],
    "dólar-turismo": ["dolar-turismo"],
    "diretor-geral": ["director-general"],
    "diretor-executivo": ["director-ejecutivo"],
    "dona-de-casa": ["ama-de-casa"],
    "lateral-direito": ["lateral-derecho"],
    "oitava-de-final": ["octavos-de-final"],
    "secretário-executivo": ["secretario-ejecutivo"],
    "obra-prima": ["obra-maestra"],
    "onça-troy": ["onza-troy"],
    "tenente-coronel": ["teniente-coronel"],
    "boca-de-urna": ["boca-de-urna"],
    "preto-branco": ["blanco-negro"],
    "sem-teto": ["sin-techo"],
    "fins-de-semana": ["fines-de-semana"],
    "não-governamental": ["no-gubernamental"],
    "diretor-superintendente": ["director-superintendente"],
    "ministro-chefe": ["ministro-jefe"],
    "editor-executivo": ["editor-ejecutivo"],
    "lua-de-mel": ["luna-de-miel"],
    "cana-de-açúcar": ["caña-de-azúcar"],
    "livro-caixa": ["libro-caja"],
    "corregedor-geral": ["corrector-general"],
    "mesa-redonda": ["mesa-redonda"],
    "quartel-general": ["cuartel-general"],
    "carro-bomba": ["coche-bomba"],
    "seguro-saúde": ["seguro-salud"],
    "gerente-geral": ["gerente-general"],
    "cardeal-arcebispo": ["cardenal-arzobispo"],
    "corpo-a-corpo": ["cuerpo-a-cuerpo"],
    "ponta-direita": ["punta-derecha"],
    "puro-sangue": ["pura-sangre"],
    "donas-de-casa": ["amas-de-casa"],
}


def get_seed_dict() -> dict[str, list[str]]:
    """Return normalized seed dictionary."""
    merged = {k.lower(): v for k, v in SEED_PT_ES.items()}
    for k, v in MANUAL_MISSING_PT_ES.items():
        merged.setdefault(k.lower(), v)
    return merged
